<?php
// $Id$
/**
 * @file
 * Mercurial backend for Version Control API - Provides Mercurial commit
 * information and account management as a pluggable backend.
 *
 * Copyright 2008 by Edward Z. Yang (ezyang, http://drupal.org/user/211688)
 */

// Mercurial PHP interface functions
include_once(drupal_get_path('module', 'versioncontrol_hg') .'/hg/hg.inc');

/**
 * Implementation of hook_versioncontrol_backends().
 *
 * @return
 *   A structured array containing information about this backend, wrapped
 *   in a structured array. Array key is the unique string identifier of
 *   the backend. The corresponding array values are again structured arrays
 *   and consist of elements with the following keys:
 *
 *   - 'name': The user-visible name of the VCS.
 *   - 'description': A short description of the backend, if possible not
 *        longer than one or two sentences.
 *   - 'capabilities': An array listing optional capabilities, in addition to
 *        the required functionality like retrieval of detailed commit
 *        information. Array values can be an arbitrary combination
 *        of VERSIONCONTROL_CAPABILITY_* values. If no additional capabilities
 *        are supported by the backend, this array will be empty.
 *   - 'flags': An array listing which tables should be managed by
 *        Version Control API instead of doing it manually in the backend.
 *        Array values can be an arbitrary combination of VERSIONCONTROL_FLAG_*
 *        values. If no array additions should be automatically managed,
 *        this array will be empty.
 */
function versioncontrol_hg_versioncontrol_backends() {
  return array(
    // The array key is up to 8 characters long, and used as unique identifier
    // for this VCS, in functions, URLs and in the database.
    'hg' => array(
      // The user-visible name of the VCS.
      'name' => 'Mercurial',

      // A short description of the VCS, if possible not longer than one or two sentences.
      'description' => t('Mercurial is a distributed revision control system written in Python.'),

      // A list of optional capabilities, in addition to the required retrieval
      // of detailed commit information. All allowed values are listed below.
      'capabilities' => array(
        // Able to retrieve a file or its revision number based on a global
        // revision identifier.
        VERSIONCONTROL_CAPABILITY_ATOMIC_COMMITS,
      ),

      // An array listing which tables should be managed by Version Control API
      // instead of doing it manually in the backend.
      // All allowed values are listed below.
      'flags' => array(
        // versioncontrol_insert_repository() will automatically insert
        // array elements from $repository['[xxx]_specific'] into
        // {versioncontrol_[xxx]_repositories} and versioncontrol_get_repositories()
        // will automatically fetch it from there.
        VERSIONCONTROL_FLAG_AUTOADD_REPOSITORIES,

        // versioncontrol_insert_commit() will automatically insert
        // array elements from $commit['[xxx]_specific'] into
        // {versioncontrol_[xxx]_commits} and versioncontrol_get_commits()
        // will automatically fetch it from there.
        VERSIONCONTROL_FLAG_AUTOADD_COMMITS,
      ),
    ),
  );
}

/**
 * Implementation of hook_cron(): Update repositories that have cron updates
 * enabled.
 */
function versioncontrol_hg_cron() {
  $result = db_query("SELECT repo_id FROM {versioncontrol_hg_repositories}
                      WHERE update_method = %d", VERSIONCONTROL_HG_UPDATE_CRON);
  // We have purposely omitted set_time_limit, as this is something that
  // should be set by cron itself and not us!
  while ($repo = db_fetch_object($result)) {
    $repository = versioncontrol_get_repository($repo->repo_id);
    if (isset($repository)) {
      _versioncontrol_hg_update_repository($repository);
    }
  }
}

/**
 * Performs all updates on a repository (currently just logs).
 */
function _versioncontrol_hg_update_repository(&$repository) {
  include_once(drupal_get_path('module', 'versioncontrol_hg') .'/versioncontrol_hg.log.inc');
  _versioncontrol_hg_log_update_repository($repository);
}

/**
 * Implementation of [versioncontrol_backend]_get_directory_item():
 * Retrieve the item of the deepest-level directory in the repository that is
 * common to all the changed/branched/tagged items in a commit, branch or
 * tag operation. In other words, this function gets you the item
 * for $operation['directory'].
 *
 * @warning
 *   I don't understand why this can't have a generic implementation.
 *
 * @param $operation
 *   The commit, branch or tag operation whose deepest-level
 *   changed/branched/tagged directory should be retrieved.
 *
 * @return
 *   The requested directory item. Item values are structured arrays and
 *   consist of elements with the following keys:
 *
 *   - 'type': Specifies the item type, which in this case can only be
 *        VERSIONCONTROL_ITEM_DIRECTORY.
 *   - 'path': The path of the directory, which will be the same
 *        as $operation['directory'].
 *   - 'revision': The (file-level) revision when the item was last changed.
 *        If there is no such revision (which may be the case for
 *        directory items) then the 'revision' element is an empty string.
 *   - '[xxx]_specific': May be set by the backend to remember additional
 *        item info. ("[xxx]" is the unique string identifier
 *        of the respective version control system.)
 */
function versioncontrol_hg_get_directory_item($operation) {
  $item = array(
    'type' => VERSIONCONTROL_ITEM_DIRECTORY,
    'path' => $operation['directory'],
    'revision' => '',
    // We removed selected_op; might need to readd it later
  );
  if (isset($operation['hg_specific']['branch_id'])) {
    $item['hg_specific']['selected_branch_id'] = $operation['hg_specific']['branch_id'];
  }
  return $item;
}

/**
 * Implementation of [versioncontrol_backend]_get_commit_branches():
 * Retrieve the branches that have been affected by the given commit.
 *
 * @warning
 *   This one could have a generic implementation too! The biggest problem
 *   is that versioncontrol doesn't directly handle branches, but if
 *   the module is going to call this function, it really ought to.
 *
 * @return
 *   An array of strings that identify a branch in the respective repository,
 *   or an empty array if no branches were affected at all. (For CVS, there
 *   should always be a exactly one branch in the resulting array.)
 */
function versioncontrol_hg_get_commit_branches($commit) {
  if (!isset($commit['hg_specific']['branch_id'])) {
    return array();
  }
  $branch = versioncontrol_get_branch($commit['hg_specific']['branch_id']);
  if (!isset($branch)) {
    // Only for database inconsistencies:
    return array();
  }
  return array($branch['branch_name']);
}

/**
 * Implementation of [versioncontrol_backend]_commit():
 * Manage (insert or delete) additional commit data in the database.
 *
 * @warning
 *   An important precondition for our particular implementation is that
 *   all earlier revisions must be in the database.
 *
 * @param $op
 *   Either 'insert' when the commit is in the process of being created,
 *   or 'delete' if it will be deleted after this function has been called.
 * @param $commit
 *   A single commit array, like the ones returned
 *   by versioncontrol_get_commits().
 * @param $commit_actions
 *   A structured array containing the exact details of what happened to
 *   each item in this commit. The structure of this array is the same as
 *   the return value of versioncontrol_get_commit_actions().
 */
function versioncontrol_hg_commit($op, $commit, $commit_actions) {
  // TODO: There is quite a bit of duplicated code here between hg,
  // git and hg; maybe item_revisions should be put in core?
  
  switch ($op) {
    case 'insert':
      foreach ($commit_actions as $path => $action) {
        
        // Determine source information for this particular path
        // based on both the commit's parent information and this
        // filename. This is *very* Mercurial-specific.
        
        $source = array();
        foreach (array(1, 2) as $k) {
          $rev = $commit['hg_specific']["parent$k"];
          $source[$k] = array();
          if ($rev == '-1' || $rev == null) {
            // No parent, so our job is really easy.
            $source[$k]['path']     = null;
            $source[$k]['vc_op_id'] = null;
            continue;
          }
          // Determine the branch of the parent
          $parent_commit = db_result(db_query(
            "SELECT branch_id FROM {versioncontrol_hg_commits}
             WHERE rev = %d",
             $rev)
          );
          if (!$parent_commit) {
            // Database inconsistency!
            $source[$k]['path']     = null;
            $source[$k]['vc_op_id'] = null;
            continue;
          }
          
          $branch_id = $parent_commit['branch_id'];
          
          // Now, let's determine the latest commit_action for this
          // path on this branch: this will be the parent revision.
          $last_vc_op_id = db_result(db_query(
            "SELECT actions.vc_op_id FROM {versioncontrol_hg_commit_actions} AS actions
            JOIN {versioncontrol_hg_commits} AS commits
            ON actions.vc_op_id = commits.vc_op_id
            WHERE actions.path = '%s' AND commits.branch_id = %d
            ORDER BY commits.rev DESC
            LIMIT 1
            ",
            $path, $branch_id));
          
          if (!$last_vc_op_id) {
            // Database inconsistency! (and code duplication!)
            $source[$k]['path']     = null;
            $source[$k]['vc_op_id'] = null;
            continue;
          }
          
          // We currently have no way of telling if a file was copied.
          $source[$k]['path'] = $path;
          $source[$k]['vc_op_id'] = $last_vc_op_id;
          
        }
        
        $commit_action_id = db_next_id('{versioncontrol_hg_commit_actions}_commit_action_id');
        
        // Use this to support nulls. Call it a nasty cludge... I think it's art. :-)
        // Commented placeholders are used to maintain parameter order.
        $s1p = ($source[1]['path'] === null) ? 'NULL /*%s*/' : "'%s'";
        $s2p = ($source[2]['path'] === null) ? 'NULL /*%s*/' : "'%s'";
        $s1v = ($source[1]['vc_op_id'] === null) ? 'NULL /*%d*/' : '%d';
        $s2v = ($source[2]['vc_op_id'] === null) ? 'NULL /*%d*/' : '%d';
        
        db_query(
          "INSERT INTO {versioncontrol_hg_commit_actions}
           (commit_action_id, vc_op_id, type, path, action,
           source1_path, source2_path, source1_vc_op_id, source2_vc_op_id)
           VALUES (%d, %d, %d, '%s', %d,
                   $s1p, $s2p, $s1v, $s2v)",
          // Primary key:
          $commit_action_id,
          // Foreign key:
          $commit['vc_op_id'],
          $action['current item']['type'],
          $path,
          $action['action'],
          // [Newline]
          $source[1]['path'],
          $source[2]['path'],
          $source[1]['vc_op_id'],
          $source[2]['vc_op_id']
        );
      }
      break;

    case 'delete':
      $result = db_query('SELECT commit_action_id
                          FROM {versioncontrol_hg_commit_actions}
                          WHERE vc_op_id = %d', $commit['vc_op_id']);

      // We have not implemented tags yet, but this is fairly sensible
      // "unhooking" of tags from the deleted revisions.
      
      //while ($revision = db_fetch_object($result)) {
      //  db_query('DELETE FROM {versioncontrol_hg_item_tags}
      //            WHERE item_revision_id = %d',
      //            $revision->item_revision_id);
      //}
      db_query('DELETE FROM {versioncontrol_hg_commit_actions}
                WHERE vc_op_id = %d', $commit['vc_op_id']);
      break;
  }
}

/**
 * Implementation of [versioncontrol_backend]_get_commit_actions():
 * Retrieve detailed information about what happened in a single commit.
 *
 * @param $commit
 *   The commit whose actions should be retrieved.
 *
 * @return
 *   A structured array containing the exact details of what happened to
 *   each item in this commit. Array keys are the current/new paths, also for
 *   VERSIONCONTROL_ACTION_DELETED actions even if the file actually doesn't
 *   exist anymore. The corresponding array values are again structured arrays
 *   and consist of elements with the following keys:
 *
 *   'action': Specifies how the item was modified.
 *             One of the predefined VERSIONCONTROL_ACTION_* values.
 *   'modified': Boolean value, specifies if a file was modified in addition
 *               to the other action in the 'action' element of the array.
 *               Only exists for the VERSIONCONTROL_ACTION_MOVED
 *               and VERSIONCONTROL_ACTION_COPIED actions.
 *   'current item': The updated state of the modified item. Exists for all
 *                   actions except VERSIONCONTROL_ACTION_DELETED.
 *   'source items': An array with the previous state(s) of the modified item.
 *                   Path and branch will always be the same as in the current
 *                   item except for the VERSIONCONTROL_ACTION_MOVED,
 *                   VERSIONCONTROL_ACTION_COPIED and
 *                   VERSIONCONTROL_ACTION_MERGED actions.
 *                   Exists for all actions except VERSIONCONTROL_ACTION_ADDED.
 *
 *   Item values are structured arrays and consist of elements
 *   with the following keys:
 *
 *   'type': Specifies the item type, which is either
 *           VERSIONCONTROL_ITEM_FILE or VERSIONCONTROL_ITEM_DIRECTORY.
 *   'path': The path of the item at the specific revision.
 *   'revision': The (file-level) revision when the item was changed.
 *               If there is no such revision (which may be the case for
 *               directory items) then the 'revision' element is
 *               an empty string.
 *   '[xxx]_specific': May be set by the backend to remember additional
 *                     item info. ("[xxx]" is the unique string identifier
 *                     of the respective version control system.)
 */
function versioncontrol_hg_get_commit_actions($commit) {
  $commit_actions = array();
  
  $result = db_query('SELECT commit_action_id, action, type, path,
                      source1_path, source2_path, source1_vc_op_id, source2_vc_op_id
                      FROM {versioncontrol_hg_commit_actions}
                      WHERE vc_op_id = %d', $commit['vc_op_id']);

  while ($raw_commit_action = db_fetch_array($result)) {
    $commit_action = array(
      'action' => $raw_commit_action['action'],
      'modified' => FALSE,
      'hg_specific' => array(
        // Some housekeeping values:
        // Not sure who would need this, but we'll keep it anyway:
        'commit_action_id' => $raw_commit_action['commit_action_id'],
        // This is for versioncontrol_hg_get_current_item_branch():
        'selected_branch_id' => $commit['hg_specific']['branch_id'],
        // Don't know who will need this yet:
        // 'selected_op' => $commit,
      ),
    );
    
    if ($raw_commit_action['action'] !== VERSIONCONTROL_ACTION_DELETED) {
      $commit_action['current item'] = array(
        'type' => $raw_commit_action['type'],
        'path' => $raw_commit_action['path'],
        'revision' => $commit['revision'],
      );
    }
    
    // Most implementations check action, but since there are only
    // two to check, we won't bother:
    $commit_action['source items'] = array();
    foreach (array(1, 2) as $k) {
      if ($raw_commit_action["source{$k}_vc_op_id"] === null) {
        continue;
      }
      // Pull the changeset node for the operation
      // We could use versioncontrol_get_commits(), but that's total
      // overkill for our needs. We could also have done a JOIN.
      $revision = db_result(db_query(
        "SELECT revision FROM {versioncontrol_commits}
        WHERE vc_op_id = %d",
        $raw_commit_action["source{$k}_vc_op_id"])
      );
      if (!$revision) {
        // Database error, abort!
        continue;
      }
      $commit_action['source items'][] = array(
        'type' => $raw_commit_action['type'],
        'path' => $raw_commit_action["source{$k}_path"],
        'revision' => $revision,
      );
    }

    $commit_actions[$raw_commit_action['path']] = $commit_action;
  }

  return $commit_actions;
}

/**
 * Implementation of [versioncontrol_backend]_get_current_item_branch():
 * Retrieve the current branch that this item is in. If this item was part of
 * the result of versioncontrol_get_commit_actions(), this will probably be
 * the branch that this item was committed to. The main branch ('HEAD' for CVS)
 * is also a valid branch and should be expected as return value.
 *
 * @param $repository
 *   The repository that the item is located in.
 * @param $item
 *   The item whose current branch should be retrieved.
 *
 * @return
 *   A string containing the current item branch, or NULL if no branch
 *   is known or applicable.
 */
function versioncontrol_hg_get_current_item_branch($repository, $item) {
  if (!isset($item['hg_specific']['selected_branch_id'])) {
    return NULL;
  }

  $branch = versioncontrol_get_branch($item['hg_specific']['selected_branch_id']);
  if (!isset($branch)) {
    return NULL;
  }
  return $branch['branch_name'];
}

// Awaiting implementation:

// function versioncontrol_hg_menu()

